-- Purple Memory Kernel — Database Schema Documentation
-- Version: 2.0
-- Engine: SQLite with FTS5 + sqlite-vec extensions
-- Location: ~/.agent/memory/purple.db
-- Last updated: 2026-02-25

-- =============================================================================
-- CORE MEMORIES TABLE
-- Stores all memory entries with metadata for attribution and classification.
-- Backward compatible with v1.0 (agent and source columns added in v2.0).
-- =============================================================================

CREATE TABLE IF NOT EXISTS memories (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    content     TEXT NOT NULL,                       -- The memory content (natural language)
    type        TEXT NOT NULL,                       -- Classification (see VALID_TYPES below)
    tags        TEXT DEFAULT '[]',                   -- JSON array of string tags
    agent       TEXT DEFAULT 'unknown',              -- Which agent stored this memory
    source      TEXT DEFAULT 'manual',               -- How it was created (manual, compiled, agent_output)
    created_at  TEXT NOT NULL,                       -- ISO 8601 UTC timestamp
    updated_at  TEXT NOT NULL                        -- ISO 8601 UTC timestamp
);

-- Performance indexes
CREATE INDEX IF NOT EXISTS idx_memories_type    ON memories(type);
CREATE INDEX IF NOT EXISTS idx_memories_created ON memories(created_at);
CREATE INDEX IF NOT EXISTS idx_memories_agent   ON memories(agent);

-- =============================================================================
-- VALID MEMORY TYPES
-- =============================================================================
-- fact          — Verified information about the world, infrastructure, or domain
-- preference    — User or organizational preferences
-- experience    — Lessons learned, outcomes of past decisions
-- correction    — A previously held belief that was found to be wrong
-- procedural    — Step-by-step workflows, how to accomplish specific tasks
-- pattern       — Recurring patterns observed across multiple interactions
-- agent_output  — Significant output from agent deliberations worth preserving

-- =============================================================================
-- VALID SOURCES
-- =============================================================================
-- manual        — Stored by human or agent during normal operation
-- compiled      — Generated by the Memory Compiler from cloud session analysis
-- agent_output  — Direct output from an agent deliberation

-- =============================================================================
-- FTS5 FULL-TEXT SEARCH INDEX
-- Provides BM25-ranked keyword search across memory content and tags.
-- Uses Porter stemming and Unicode-aware tokenization.
-- Kept in sync with memories table via triggers.
-- =============================================================================

CREATE VIRTUAL TABLE IF NOT EXISTS memories_fts USING fts5(
    content,
    tags,
    content='memories',
    content_rowid='id',
    tokenize='porter unicode61'
);

-- Sync triggers: keep FTS5 index in sync with memories table
CREATE TRIGGER IF NOT EXISTS memories_ai AFTER INSERT ON memories BEGIN
    INSERT INTO memories_fts(rowid, content, tags)
    VALUES (new.id, new.content, new.tags);
END;

CREATE TRIGGER IF NOT EXISTS memories_ad AFTER DELETE ON memories BEGIN
    INSERT INTO memories_fts(memories_fts, rowid, content, tags)
    VALUES ('delete', old.id, old.content, old.tags);
END;

CREATE TRIGGER IF NOT EXISTS memories_au AFTER UPDATE ON memories BEGIN
    INSERT INTO memories_fts(memories_fts, rowid, content, tags)
    VALUES ('delete', old.id, old.content, old.tags);
    INSERT INTO memories_fts(rowid, content, tags)
    VALUES (new.id, new.content, new.tags);
END;

-- =============================================================================
-- VECTOR EMBEDDING TABLE (sqlite-vec)
-- Stores 768-dimensional float32 embeddings from nomic-embed-text v1.5.
-- Enables semantic similarity search via cosine distance.
-- Only created if sqlite-vec extension is available.
-- =============================================================================

-- Requires: pip install sqlite-vec
-- Model: nomic-embed-text (137M params, 768d, 8192 token context, MTEB 62.39)
-- Served via: Ollama /api/embed endpoint

CREATE VIRTUAL TABLE IF NOT EXISTS memories_vec
USING vec0(embedding float[768]);

-- =============================================================================
-- SEARCH STRATEGY: Reciprocal Rank Fusion (RRF)
-- =============================================================================
-- When both FTS5 and sqlite-vec are available, search results are combined
-- using RRF with k=60:
--
--   score(doc) = SUM( 1 / (k + rank_in_source) ) across all sources
--
-- This gives equal weight to keyword matches (FTS5) and semantic matches
-- (vector similarity), producing results that satisfy both literal and
-- conceptual relevance.
--
-- Fallback chain:
--   1. Hybrid (FTS5 + vector) — if sqlite-vec is available and Ollama is running
--   2. FTS5 only — if sqlite-vec is unavailable
--   3. LIKE search — if FTS5 returns no results (edge case: special characters)

-- =============================================================================
-- ACCESS CONTROL (enforced in application layer, not SQL)
-- =============================================================================
-- Purple Admin:       Full read/write to all memories
-- E.I.K. Advisory:    Full read, write with agent attribution
-- Operational Staff:  Read (filtered by domain relevance), no direct write
--
-- See CHARTER.md Section 6 for complete access matrix.

-- =============================================================================
-- FUTURE EXTENSIONS (not yet implemented)
-- =============================================================================
-- confidence     REAL DEFAULT 1.0      -- Confidence score (0.0 to 1.0)
-- valid_from     TEXT                   -- Temporal validity start (ISO 8601)
-- valid_until    TEXT                   -- Temporal validity end (ISO 8601)
-- access_count   INTEGER DEFAULT 0     -- Number of times retrieved
-- last_accessed  TEXT                   -- Last retrieval timestamp
-- parent_id      INTEGER               -- For memory chains/threads
--
-- These fields are documented for the Phase 3 consolidation engine.
-- They will be added via ALTER TABLE when the consolidator is deployed.
